In [1]:
import pandas as pd

In [ ]:
#Save DataFrame to a CSV file
df.to_csv("people.csv", index=False)

In [ ]:
df.to_excel("people.xlsx", index=False)

In [ ]:
df.to_excel("people.xlsx", index=False, sheet_name="Sheet1")

In [ ]:
df.to_json("people.json", orient="records")
#Produces a list of row objects (each row becomes a JSON object).

In [ ]:
df.to_json("people.json", orient="records", indent=4)

In [ ]:
# creating

In [1]:
arr = np.array([
    [[4, 2], [6, 4]],
    [[5, 6], [17, 8]]
])

NameError: name 'np' is not defined

In [ ]:
arr.reshape(2, 3)  #Can convert to any shape (if elements match)

# Ravel()

In [ ]:
#Converts array into 1D (flatten)

In [4]:
arr.ravel()   ##Changes in result affect original array

array([ 4,  2,  6,  4,  5,  6, 17,  8])

In [5]:
flat = arr.ravel()
flat[0] = 100

In [6]:
flat

array([100,   2,   6,   4,   5,   6,  17,   8])

In [7]:
arr

array([[[100,   2],
        [  6,   4]],

       [[  5,   6],
        [ 17,   8]]])

# flatten()

In [ ]:
arr.flatten() #Returns a copy (new memory)  means not change in original arrary

# Using Nested List

In [9]:
import pandas as pd

data = [
    [1, "Renu", 23, "Meerut"],
    [2, "Amit", 25, "Delhi"],
    [3, "Neha", 22, "Noida"]
]
a=["ID", "Name", "Age", "City"]
df = pd.DataFrame(data, columns=a)
print(df)

   ID  Name  Age    City
0   1  Renu   23  Meerut
1   2  Amit   25   Delhi
2   3  Neha   22   Noida

# using list of dict

In [10]:
data = [
    {"ID": 1, "Name": "Renu", "Age": 23, "City": "Meerut"},
    {"ID": 2, "Name": "Amit", "Age": 25, "City": "Delhi"},
    {"ID": 3, "Name": "Neha", "Age": 22, "City": "Noida"}
]

df = pd.DataFrame(data)
print(df)

   ID  Name  Age    City
0   1  Renu   23  Meerut
1   2  Amit   25   Delhi
2   3  Neha   22   Noida

# using dict of list

In [11]:
import pandas as pd    # columnar format

data = {
    "ID": [1, 2, 3],
    "Name": ["Renu", "Amit", "Neha"],
    "Age": [23, 25, 22],
    "City": ["Meerut", "Delhi", "Noida"]
}

df = pd.DataFrame(data)
print(df)

   ID  Name  Age    City
0   1  Renu   23  Meerut
1   2  Amit   25   Delhi
2   3  Neha   22   Noida

In [ ]:
# DataFrame from Nested Dictionary (dict inside dict)

In [12]:
data = {
    0: {"ID": 1, "Name": "Renu", "Age": 23, "City": "Meerut"},
    1: {"ID": 2, "Name": "Amit", "Age": 25, "City": "Delhi"},
    2: {"ID": 3, "Name": "Neha", "Age": 22, "City": "Noida"}
}

df = pd.DataFrame.from_dict(data, orient='index')
print(df)

   ID  Name  Age    City
0   1  Renu   23  Meerut
1   2  Amit   25   Delhi
2   3  Neha   22   Noida

In [ ]:
# Convert 3D NumPy Array → DataFrame

In [2]:
import numpy as np
import pandas as pd

arr = np.array([
    [[4, 2], [6, 4]],
    [[5, 6], [17, 8]]
])

In [3]:
arr.reshape(-1, 2) # not change in original array

array([[ 4,  2],
       [ 6,  4],
       [ 5,  6],
       [17,  8]])

In [2]:
df = pd.DataFrame(arr.reshape(-1, 2), columns=["Col1", "Col2"])
print(df)

   Col1  Col2
0     4     2
1     6     4
2     5     6
3    17     8

In [4]:
arr.reshape(1, -1) # 1 row and columns auto-calculated

array([[ 4,  2,  6,  4,  5,  6, 17,  8]])

# reading a csv file

In [8]:
s= pd.read_csv("D:\simple_data.csv")
s

    id name   age
0  1.0    A  25.0
1  2.0    B  25.0
2  3.0    C  28.0
3  4.0    D  33.0
4  NaN    E   NaN

In [12]:
s[['age','name']]

    age name
0  25.0    A
1  25.0    B
2  28.0    C
3  33.0    D
4   NaN    E

In [12]:
s[['name','id']]    #select

  name   id
0    A  1.0
1    B  2.0
2    C  3.0
3    D  4.0
4    E  NaN

In [14]:
s['id'].dtypes
#ser

dtype('float64')

In [15]:
s.values

array([[1.0, 'A', 25.0],
       [2.0, 'B', 25.0],
       [3.0, 'C', 28.0],
       [4.0, 'D', 33.0],
       [nan, 'E', nan]], dtype=object)

In [16]:
col=s.columns
col

Index(['id', 'name', 'age'], dtype='object')

In [17]:
s

    id name   age
0  1.0    A  25.0
1  2.0    B  25.0
2  3.0    C  28.0
3  4.0    D  33.0
4  NaN    E   NaN

In [6]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
s['name']

0    A
1    B
2    C
3    D
Name: name, dtype: object

In [ ]:
print(

# parameters of .read_csv

In [ ]:
sep='\t',',','-','_'
names=['emp_id','c2'] #Custom column names
index_col='c2' # which column you want to make index
header=1 # Row number used as header, or None header: 
#row number to use as the column headers (default is the first row);
usecols=['c1','c2'] # colmn you want to include in your database 
nrows=100
na_values=(["NA", "Missing"])   #Additional strings to treat as NaN
skiprows              #Skip initial rows

In [39]:
s = pd.read_csv("D:\simple_data.csv",names=['empid','empname'],header=0,index_col='empname',usecols=['empid','empname'],na_values=0,nrows=2)
s['empid']

empname
A    1
B    2
Name: empid, dtype: int64

In [40]:
s = pd.read_csv("D:\simple_data.csv")

In [41]:
s

    id name   age
0  1.0    A  25.0
1  2.0    B  25.0
2  3.0    C  28.0
3  4.0    D  33.0
4  NaN    E   NaN

In [ ]:
s

In [ ]:
pd.read_excel("file.xlsx", sheet_name="Sheet1")

In [14]:
pd.read_json("data30.json")

    name  age  marks
0  Alice   21     88
1  Alice   21     92
2  Alice   21     79

#  from a web link (URL)

In [ ]:
df = pd.read_csv("https://example.com/data.csv")

In [52]:
df = pd.read_csv("D:\sql intro.txt", sep="\t",names=['col1'])

In [62]:
df

                                                 col1
0   “Imagine you’re in a giant library with millio...
1   That’s exactly what SQL does—but for data inst...
2                                    What Can SQL do?
3         SQL can execute queries against a database
4              SQL can retrieve data from a database
5               SQL can insert records in a database
6               SQL can update records in a database
7             SQL can delete records from a database
8                       SQL can create new databases
9            SQL can create new tables in a database
10    SQL can create stored procedures in a database
11                SQL can create views in a database
12  SQL can set permissions on tables, procedures...
13   organize information, and get clear answers q...
14  It’s simple, logical, and one of the most impo...
15  “Let’s start with a simple thought—data is the...
16  SQL, which stands for Structured Query Languag...
17    Now, let’s go over the key features one by one:
18  Data Definition: This is all about creating an...
19  Data Manipulation: Once the structure is ready...
20  Data Control: Not everyone should have access ...
21  Transaction Control: Imagine you’re shopping o...
22  So, SQL is not just about storing data—it’s ab...
23  And here’s the exciting part—in the coming ses...
24     “Now let’s talk about why we should learn SQL.
25  First, SQL works with almost all major databas...
26  It’s also a skill in very high demand. Data an...
27  Another reason—it’s essential for data manipul...
28  And the best part—it’s easy to learn, yet powe...
29  Now, let’s highlight some key advantages of SQ...
30  Ease of Use: SQL is written in simple, English...
31  Efficient Data Handling: SQL can handle massiv...
32  Standardized Language: SQL is an international...
33  Scalability: SQL can be used for both small pr...
34  Integration: SQL easily connects with other la...
35  So, to summarize—SQL is universal, powerful, a...

In [61]:
df.iloc[:1,0]

0    “Imagine you’re in a giant library with millio...
Name: col1, dtype: object

In [2]:
df=pd.read_csv("D:\samples_data.csv")
df

   id     name    age   gender     salary   join_date department  score
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
3   4    david   45.0     male        NaN          IT        NaN    NaN
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [6]:
pd.set_option("display.max_rows",300)
pd.set_option("display.max_columns",300)

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
dic={"name":['renu','ritu']}
df=pd.dataframe(dic)
df

AttributeError: module 'pandas' has no attribute 'dataframe'

In [64]:
df

   id     name    age   gender     salary   join_date department  score
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
3   4    david   45.0     male        NaN          IT        NaN    NaN
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [68]:
df.head(3) # top rows

   id     name   age gender   salary   join_date department  score
0   1    Alice  25.0      F  50000.0  2021-05-10      Sales   88.0
1   2      Bob  30.0      M  62000.0  2020/03/15         HR   92.0
2   3  Charlie   NaN      M  58000.0  15-07-2019         IT   79.0

In [69]:
df.tail(3)

   id     name   age   gender   salary   join_date department  score
7   8      NaN  29.0   FEMALE  51000.0  2021-09-01      Sales   85.0
8   9   Grace    NaN        F  49000.0  2020/12/01      SALES   90.0
9  10    Henry  41.0  Unknown      NaN  2017-05-05         IT   82.0

In [70]:
df.columns

Index(['id', 'name', 'age', 'gender', 'salary', 'join_date', 'department',
       'score'],
      dtype='object')

In [72]:
df[['id','name','score']]

   id     name  score
0   1    Alice   88.0
1   2      Bob   92.0
2   3  Charlie   79.0
3   4    david    NaN
4   5      Eve   65.0
5   5      Eve  300.0
6   7    Frank   73.0
7   8      NaN   85.0
8   9   Grace    90.0
9  10    Henry   82.0

In [10]:
df[['id', 'name', 'age', 'gender', 'salary', 'join_date']]

   id     name    age   gender     salary   join_date
0   1    Alice   25.0        F    50000.0  2021-05-10
1   2      Bob   30.0        M    62000.0  2020/03/15
2   3  Charlie    NaN        M    58000.0  15-07-2019
3   4    david   45.0     male        NaN          IT
4   5      Eve   -3.0        F    72000.0  2022-13-01
5   5      Eve  200.0      NaN  1000000.0  2018-11-20
6   7    Frank   33.0        M    54000.0  wrong_date
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01
8   9   Grace     NaN        F    49000.0  2020/12/01
9  10    Henry   41.0  Unknown        NaN  2017-05-05

# dataframe attribute and methods

In [14]:
df.shape

(10, 8)

In [21]:
df.dtypes

id              int64
name           object
age           float64
gender         object
salary        float64
join_date      object
department     object
score         float64
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        9 non-null      object
 2   age         8 non-null      float64
 3   gender      9 non-null      object
 4   salary      8 non-null      float64
 5   join_date   10 non-null     object
 6   department  8 non-null      object
 7   score       9 non-null      float64
dtypes: float64(3), int64(1), object(4)
memory usage: 772.0+ bytes

In [10]:
len(df.columns)

8

In [16]:
df.values

array([[1, 'Alice', 25.0, 'F', 50000.0, '2021-05-10', 'Sales', 88.0],
       [2, 'Bob', 30.0, 'M', 62000.0, '2020/03/15', 'HR', 92.0],
       [3, 'Charlie', nan, 'M', 58000.0, '15-07-2019', 'IT', 79.0],
       [4, 'david', 45.0, 'male', nan, 'IT', nan, nan],
       [5, 'Eve', -3.0, 'F', 72000.0, '2022-13-01', nan, 65.0],
       [5, 'Eve', 200.0, nan, 1000000.0, '2018-11-20', 'Finance', 300.0],
       [7, 'Frank', 33.0, 'M', 54000.0, 'wrong_date', 'finance', 73.0],
       [8, nan, 29.0, 'FEMALE', 51000.0, '2021-09-01', 'Sales', 85.0],
       [9, ' Grace ', nan, 'F', 49000.0, '2020/12/01', 'SALES', 90.0],
       [10, 'Henry', 41.0, 'Unknown', nan, '2017-05-05', 'IT', 82.0]],
      dtype=object)

In [74]:
df.tail(10)

   id     name    age   gender     salary   join_date department  score
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
3   4    david   45.0     male        NaN          IT        NaN    NaN
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        9 non-null      object
 2   age         8 non-null      float64
 3   gender      9 non-null      object
 4   salary      8 non-null      float64
 5   join_date   9 non-null      object
 6   department  9 non-null      object
 7   score       9 non-null      float64
dtypes: float64(3), int64(1), object(4)
memory usage: 772.0+ bytes

In [ ]:
This function produces descriptive statistics for the DataFrame, that is, the central tendency (mean, median, min, max, etc.), dispersion, etc. It analyses the data and generates an output for both numeric and non-numeric data types accordingly.

In [75]:
df.describe()

              id         age          salary       score
count  10.000000    8.000000        8.000000    9.000000
mean    5.400000   50.000000   174500.000000  106.000000
std     3.025815   62.301112   333639.668762   73.252986
min     1.000000   -3.000000    49000.000000   65.000000
25%     3.250000   28.000000    50750.000000   79.000000
50%     5.000000   31.500000    56000.000000   85.000000
75%     7.750000   42.000000    64500.000000   90.000000
max    10.000000  200.000000  1000000.000000  300.000000

In [19]:
df.describe(include='all')

,id,name,age,gender,salary,join_date,department,score
count,10.000000,9,8.000000,9,8.000000,10,8,9.000000
unique,NaN,8,NaN,5,NaN,10,6,NaN
top,NaN,Eve,NaN,F,NaN,2021-05-10,Sales,NaN
freq,NaN,2,NaN,3,NaN,1,2,NaN
mean,5.400000,NaN,50.000000,NaN,174500.000000,NaN,NaN,106.000000
std,3.025815,NaN,62.301112,NaN,333639.668762,NaN,NaN,73.252986
min,1.000000,NaN,-3.000000,NaN,49000.000000,NaN,NaN,65.000000
25%,3.250000,NaN,28.000000,NaN,50750.000000,NaN,NaN,79.000000
50%,5.000000,NaN,31.500000,NaN,56000.000000,NaN,NaN,85.000000
75%,7.750000,NaN,42.000000,NaN,64500.000000,NaN,NaN,90.000000
max,10.000000,NaN,200.000000,NaN,1000000.000000,NaN,NaN,300.000000

In [10]:
df.describe(percentiles=[0.1, 0.25, 0.5, 0.80, 0.9])

              id         age          salary       score
count  10.000000    8.000000        8.000000    9.000000
mean    5.400000   50.000000   174500.000000  106.000000
std     3.025815   62.301112   333639.668762   73.252986
min     1.000000   -3.000000    49000.000000   65.000000
10%     1.900000   16.600000    49700.000000   71.400000
25%     3.250000   28.000000    50750.000000   79.000000
50%     5.000000   31.500000    56000.000000   85.000000
75%     7.750000   42.000000    64500.000000   90.000000
90%     9.100000   91.500000   350400.000000  133.600000
max    10.000000  200.000000  1000000.000000  300.000000

In [77]:
df.describe(percentiles=[0.80])

              id         age          salary       score
count  10.000000    8.000000        8.000000    9.000000
mean    5.400000   50.000000   174500.000000  106.000000
std     3.025815   62.301112   333639.668762   73.252986
min     1.000000   -3.000000    49000.000000   65.000000
50%     5.000000   31.500000    56000.000000   85.000000
80%     8.200000   43.400000    68000.000000   90.800000
max    10.000000  200.000000  1000000.000000  300.000000

# functions

In [ ]:
value_count()
sort_value(ascending=False)
sort_index
set_index
rename
reset_index
unique
nunique
isnull
not null
has nan
dropna
fillna
drop_duplicates
drop
apply
isin

In [15]:
df['gender'].value_counts()

gender
F          3
M          3
male       1
FEMALE     1
Unknown    1
Name: count, dtype: int64

In [16]:
df['department'].value_counts()

department
Sales      2
IT         2
HR         1
Finance    1
finance    1
SALES      1
Name: count, dtype: int64

In [17]:
df['gender'].unique()

array(['F', 'M', 'male', nan, 'FEMALE', 'Unknown'], dtype=object)

In [18]:
df['gender'].nunique()

5

In [79]:
df['gender'].unique()

array(['female', 'male', nan], dtype=object)

In [30]:
df.shape

(10, 7)

In [85]:
df

   id     name    age   gender     salary   join_date department  score
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
3   4    david   45.0     male        NaN          IT        NaN    NaN
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [91]:
df=df.set_index(['name'])

In [92]:
df

         id    age   gender     salary   join_date department  score
name
Alice     1   25.0        F    50000.0  2021-05-10      Sales   88.0
Bob       2   30.0        M    62000.0  2020/03/15         HR   92.0
Charlie   3    NaN        M    58000.0  15-07-2019         IT   79.0
david     4   45.0     male        NaN          IT        NaN    NaN
Eve       5   -3.0        F    72000.0  2022-13-01        NaN   65.0
Eve       5  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
Frank     7   33.0        M    54000.0  wrong_date    finance   73.0
NaN       8   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
 Grace    9    NaN        F    49000.0  2020/12/01      SALES   90.0
Henry    10   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [93]:
df

         id    age   gender     salary   join_date department  score
name
Alice     1   25.0        F    50000.0  2021-05-10      Sales   88.0
Bob       2   30.0        M    62000.0  2020/03/15         HR   92.0
Charlie   3    NaN        M    58000.0  15-07-2019         IT   79.0
david     4   45.0     male        NaN          IT        NaN    NaN
Eve       5   -3.0        F    72000.0  2022-13-01        NaN   65.0
Eve       5  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
Frank     7   33.0        M    54000.0  wrong_date    finance   73.0
NaN       8   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
 Grace    9    NaN        F    49000.0  2020/12/01      SALES   90.0
Henry    10   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [80]:
df.set_index(['id'],inplace=True)

In [94]:
df

         id    age   gender     salary   join_date department  score
name
Alice     1   25.0        F    50000.0  2021-05-10      Sales   88.0
Bob       2   30.0        M    62000.0  2020/03/15         HR   92.0
Charlie   3    NaN        M    58000.0  15-07-2019         IT   79.0
david     4   45.0     male        NaN          IT        NaN    NaN
Eve       5   -3.0        F    72000.0  2022-13-01        NaN   65.0
Eve       5  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
Frank     7   33.0        M    54000.0  wrong_date    finance   73.0
NaN       8   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
 Grace    9    NaN        F    49000.0  2020/12/01      SALES   90.0
Henry    10   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [95]:
df.sort_values('score',ascending=False) # desc

         id    age   gender     salary   join_date department  score
name
Eve       5  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
Bob       2   30.0        M    62000.0  2020/03/15         HR   92.0
 Grace    9    NaN        F    49000.0  2020/12/01      SALES   90.0
Alice     1   25.0        F    50000.0  2021-05-10      Sales   88.0
NaN       8   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
Henry    10   41.0  Unknown        NaN  2017-05-05         IT   82.0
Charlie   3    NaN        M    58000.0  15-07-2019         IT   79.0
Frank     7   33.0        M    54000.0  wrong_date    finance   73.0
Eve       5   -3.0        F    72000.0  2022-13-01        NaN   65.0
david     4   45.0     male        NaN          IT        NaN    NaN

In [3]:
df=df.sort_values(['salary','score'],ascending=[True,False])

In [4]:
df

   id     name    age   gender     salary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

In [32]:
#This sorts the rows in ascending order of the index.
df.sort_index()

       name    age  gender     salary   join_date department  score
id
1     Alice   25.0  female    50000.0  2021-05-10      Sales   88.0
2       Bob   30.0    male    62000.0  2020/03/15         HR   92.0
3   Charlie    NaN    male    58000.0  15-07-2019         IT   79.0
4     david   45.0     NaN        NaN          IT        NaN    NaN
5       Eve   -3.0  female    72000.0  2022-13-01        NaN   65.0
5       Eve  200.0     NaN  1000000.0  2018-11-20    Finance  300.0
7     Frank   33.0    male    54000.0  wrong_date    finance   73.0
8       NaN   29.0  female    51000.0  2021-09-01      Sales   85.0
9    Grace     NaN  female    49000.0  2020/12/01      SALES   90.0
10    Henry   41.0     NaN        NaN  2017-05-05         IT   82.0

In [5]:
df.sort_index(ascending=False)

   id     name    age   gender     salary   join_date department  score
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
3   4    david   45.0     male        NaN          IT        NaN    NaN
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0

In [36]:
df.sort_index(axis=1) # sort by column name

      age department  gender   join_date     name     salary  score
id
1    25.0      Sales  female  2021-05-10    Alice    50000.0   88.0
2    30.0         HR    male  2020/03/15      Bob    62000.0   92.0
3     NaN         IT    male  15-07-2019  Charlie    58000.0   79.0
4    45.0        NaN     NaN          IT    david        NaN    NaN
5    -3.0        NaN  female  2022-13-01      Eve    72000.0   65.0
5   200.0    Finance     NaN  2018-11-20      Eve  1000000.0  300.0
7    33.0    finance    male  wrong_date    Frank    54000.0   73.0
8    29.0      Sales  female  2021-09-01      NaN    51000.0   85.0
9     NaN      SALES  female  2020/12/01   Grace     49000.0   90.0
10   41.0         IT     NaN  2017-05-05    Henry        NaN   82.0

In [6]:
#Rename a single column
#df.rename(columns={"old_name": "new_name"}, inplace=True)
df.rename(columns={"name": "ename", "salary": "esalary"}, inplace=True)

In [7]:
df

   id    ename    age   gender    esalary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

# Handling the null values

In [10]:
df.isnull().sum() # df.isna() same

id            0
ename         1
age           2
gender        1
esalary       2
join_date     0
department    2
score         1
dtype: int64

In [41]:
df.isna()

      id  ename    age  gender  esalary  join_date  department  score
0  False  False  False   False    False      False       False  False
1  False  False  False   False    False      False       False  False
2  False  False   True   False    False      False       False  False
3  False  False  False    True     True      False        True   True
4  False  False  False   False    False      False        True  False
5  False  False  False    True    False      False       False  False
6  False  False  False   False    False      False       False  False
7  False   True  False   False    False      False       False  False
8  False  False   True   False    False      False       False  False
9  False  False  False    True     True      False       False  False

# drop nulls

In [ ]:
axis = 0 (by default) Drops rows
axis = 1 Drops columns

inplace = True    Modifies the original DataFrame
inplace = False (default)          Creates a new DataFrame

In [11]:
df

   id    ename    age   gender    esalary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

In [13]:
df.dropna(how="any",ignore_index=True)  # delete all row having single null value

   id  ename   age gender  esalary   join_date department  score
0   1  Alice  25.0      F  50000.0  2021-05-10      Sales   88.0
1   7  Frank  33.0      M  54000.0  wrong_date    finance   73.0
2   2    Bob  30.0      M  62000.0  2020/03/15         HR   92.0

In [44]:
df.dropna(how="all") #Drop rows only if ALL values are null

   id    ename    age  gender    esalary   join_date department  score
0   1    Alice   25.0  female    50000.0  2021-05-10      Sales   88.0
1   2      Bob   30.0    male    62000.0  2020/03/15         HR   92.0
2   3  Charlie    NaN    male    58000.0  15-07-2019         IT   79.0
3   4    david   45.0     NaN        NaN          IT        NaN    NaN
4   5      Eve   -3.0  female    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0     NaN  1000000.0  2018-11-20    Finance  300.0
6   7    Frank   33.0    male    54000.0  wrong_date    finance   73.0
7   8      NaN   29.0  female    51000.0  2021-09-01      Sales   85.0
8   9   Grace     NaN  female    49000.0  2020/12/01      SALES   90.0
9  10    Henry   41.0     NaN        NaN  2017-05-05         IT   82.0

In [50]:
df.dropna(subset=["age", "esalary"],ignore_index=True)#Drop rows with nulls in specific columns

   id  ename   age  gender  esalary   join_date department  score
0   1  Alice  25.0  female  50000.0  2021-05-10      Sales   88.0
1   2    Bob  30.0    male  62000.0  2020/03/15         HR   92.0
2   7  Frank  33.0    male  54000.0  wrong_date    finance   73.0

# drop column

In [49]:
 df.drop('age', axis=1)

   id  ename  gender  esalary   join_date department  score
0   1  Alice  female  50000.0  2021-05-10      Sales   88.0
1   2    Bob    male  62000.0  2020/03/15         HR   92.0
6   7  Frank    male  54000.0  wrong_date    finance   73.0

In [ ]:
#df = df.drop(['col1', 'col2'], axis=1)

In [ ]:
del df['column_name']

In [ ]:
df.pop('column_name')

# fillna

In [ ]:
df.fillna("not_defined") # replace all null with "not defined"

In [14]:
df["age"].fillna(0)     # replace age null with 0

8      0.0
0     25.0
7     29.0
6     33.0
2      0.0
1     30.0
4     -3.0
5    200.0
9     41.0
3     45.0
Name: age, dtype: float64

In [15]:
df

   id    ename    age   gender    esalary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

In [ ]:
df["salary"] = df["salary"].fillna(df["salary"].median())

In [ ]:
df["gender"] = df["gender"].fillna(df["gender"].mode()[0]) # return series 
#mode() calculates the most frequent value in the column

# drop duplicates

# Detect Duplicates

In [16]:
#Check which rows are duplicates
df.duplicated()
#Returns a Boolean Series (True if the row is a duplicate, False otherwise).

8    False
0    False
7    False
6    False
2    False
1    False
4    False
5    False
9    False
3    False
dtype: bool

In [22]:
#Check duplicates in a specific column
df.duplicated(subset=["id"])

8    False
0    False
7    False
6    False
2    False
1    False
4    False
5     True
9    False
3    False
dtype: bool

In [ ]:
# drop duplicates

In [20]:
#Drop duplicate rows based on all columns
df.drop_duplicates(inplace=True,keep="first")

In [21]:
df

   id    ename    age   gender    esalary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
4   5      Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

In [ ]:
#Drop duplicates row  based on specific columns
df.drop_duplicates(subset=["id"], inplace=True)
#Keeps the first occurrence by default.

In [23]:
#Keep last occurrence instead of first
df.drop_duplicates(subset=["id"], keep="last", inplace=True)

In [24]:
df

   id    ename    age   gender    esalary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

In [ ]:
#Drop all duplicates (keep none)
df.drop_duplicates(subset=["id"], keep=False, inplace=True)
#Removes all rows that have duplicates in the subset.

In [25]:
# Count duplicates

df.duplicated().sum()          # Count duplicates in all columns

np.int64(0)

# rename column

In [ ]:
#Rename a single column
df.rename(columns={"old_name": "new_name"}, inplace=True)
df.rename(columns={"age": "Age", "salary": "Salary_USD"}, inplace=True)

# Drop Columns

In [ ]:
#Drop a  unnecessary single column
df.drop("column_name", axis=1, inplace=True)

In [ ]:
#Drop multiple columns
df.drop(["score", "join_date"], axis=1, inplace=True)

# acess the row

In [12]:
df

   id      name    age   gender     salary   join_date department  score
0   1     Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
1   2       Bob   30.0        M    62000.0  2020/03/15         HR   92.0
2   3   Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
3   4     david   45.0     male        NaN         NaN         IT    NaN
4   5       Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5       Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
6   7     Frank   33.0        M    54000.0  wrong_date    finance   73.0
7   8       NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
8   9    Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
9  10     Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [26]:
df['id']

8     9
0     1
7     8
6     7
2     3
1     2
5     5
9    10
3     4
Name: id, dtype: int64

In [29]:
df

   id    ename    age   gender    esalary   join_date department  score
8   9   Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
0   1    Alice   25.0        F    50000.0  2021-05-10      Sales   88.0
7   8      NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
6   7    Frank   33.0        M    54000.0  wrong_date    finance   73.0
2   3  Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
1   2      Bob   30.0        M    62000.0  2020/03/15         HR   92.0
5   5      Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
9  10    Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0
3   4    david   45.0     male        NaN          IT        NaN    NaN

In [27]:
df[['id']]

   id
8   9
0   1
7   8
6   7
2   3
1   2
5   5
9  10
3   4

In [30]:
df[['id','ename','age']]

   id    ename    age
8   9   Grace     NaN
0   1    Alice   25.0
7   8      NaN   29.0
6   7    Frank   33.0
2   3  Charlie    NaN
1   2      Bob   30.0
5   5      Eve  200.0
9  10    Henry   41.0
3   4    david   45.0

# Rows filtering

In [59]:
df.loc[1:4]    #label,index,include

   id     name   age gender   salary   join_date department  score
1   2      Bob  30.0      M  62000.0  2020/03/15         HR   92.0
2   3  Charlie   NaN      M  58000.0  15-07-2019         IT   79.0
3   4    david  45.0   male      NaN          IT        NaN    NaN
4   5      Eve  -3.0      F  72000.0  2022-13-01        NaN   65.0

In [31]:
df.loc[[1,2,3,7]]

   id    ename   age  gender  esalary   join_date department  score
1   2      Bob  30.0       M  62000.0  2020/03/15         HR   92.0
2   3  Charlie   NaN       M  58000.0  15-07-2019         IT   79.0
3   4    david  45.0    male      NaN          IT        NaN    NaN
7   8      NaN  29.0  FEMALE  51000.0  2021-09-01      Sales   85.0

In [61]:
df.loc[1:5:2]

   id   name    age gender     salary   join_date department  score
1   2    Bob   30.0      M    62000.0  2020/03/15         HR   92.0
3   4  david   45.0   male        NaN          IT        NaN    NaN
5   5    Eve  200.0    NaN  1000000.0  2018-11-20    Finance  300.0

In [62]:
# fetch row +some columns
df.loc[1:5,['id','name']] # all include

   id     name
1   2      Bob
2   3  Charlie
3   4    david
4   5      Eve
5   5      Eve

In [18]:
df.loc[[1,3,5,6],['id','name']]

   id   name
1   2    Bob
3   4  david
5   5    Eve
6   7  Frank

In [19]:
df.iloc[0:4,0:2]  # exclude  ,index

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    david

In [22]:
df.iloc[:1, :]

   id   name   age gender   salary   join_date department  score
0   1  Alice  25.0      F  50000.0  2021-05-10      Sales   88.0

In [21]:
df.iloc[1:, :]

   id      name    age   gender     salary   join_date department  score
1   2       Bob   30.0        M    62000.0  2020/03/15         HR   92.0
2   3   Charlie    NaN        M    58000.0  15-07-2019         IT   79.0
3   4     david   45.0     male        NaN         NaN         IT    NaN
4   5       Eve   -3.0        F    72000.0  2022-13-01        NaN   65.0
5   5       Eve  200.0      NaN  1000000.0  2018-11-20    Finance  300.0
6   7     Frank   33.0        M    54000.0  wrong_date    finance   73.0
7   8       NaN   29.0   FEMALE    51000.0  2021-09-01      Sales   85.0
8   9    Grace     NaN        F    49000.0  2020/12/01      SALES   90.0
9  10     Henry   41.0  Unknown        NaN  2017-05-05         IT   82.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 8 to 3
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9 non-null      int64
 1   ename       8 non-null      object
 2   age         7 non-null      float64
 3   gender      8 non-null      category
 4   esalary     7 non-null      float64
 5   join_date   9 non-null      object
 6   department  8 non-null      category
 7   score       8 non-null      float64
dtypes: category(2), float64(3), int64(1), object(2)
memory usage: 1.2+ KB

In [34]:
#Convert text columns to categorical
#For columns with limited categories like gender or department:

df["gender"] = df["gender"].astype("category")
df["department"] = df["department"].astype("category")

#Benefits:
#Reduces memory usage
#Faster groupby / filtering

# ADVANCED PANDAS

In [ ]:
Merging and Concatenating DataFrames